### ISSUE TITLE
支援コンテンツの追加と変更

### ISSUE THREAD

**Issue by fujisawa-e** [Shiga-pref-org/covid19-flow#1]
1. 第一階層の追加と名称変更
- 「子どもの休校で働けない」を追加
- 「家賃が払えない」＝＞「住宅を確保して欲しい」名称変更

2. 支援コンテンツの追加
- 家賃の支払いを支援ページの問い合わせ先をPDFから表に変更
- 県営住宅での一時的な受け入れページを追加
- 小学校休業等対応助成金（事業主向け）ページを追加
- 小学校休業等対応助成金（個人向け）ページを追加
- 手元に資金がないページの一部修正、総合支援資金の追加

**Comment by kamataryo** [comment]
done at #2
